### ISSUE TITLE
Websocket read failure: ContinuationNotStarted

### ISSUE THREAD

**Issue by pdavydov108** [swimos/ratchet#30]
Hi, thanks for this library and for your awesome work! I have a question about a weird issue that I've run into. I'm trying to implement a proxy server application, that listens on an address and when a new client arrives it connects to another server and resends data to that server and replies back to the client. So I do smth like this:
```rust
// client is the connection to another server
// server is the connection that I have accepted
loop {
    tokio::select! {
        client_result = client.read(&mut buf_client) => {
             match client_result {
                 Message::Text => {
                     server.write(&mut buf_client).await?;
                     buf_client.clear();
                 }
             }
         }
         server_result = server.read(&mut buf_client) => {
              match server_result {
                  Message::Text => {
                      client.write(&mut buf_server).await?;
                      buf_server.clear();
                  }
              }
         }
    }
}
```
The issue is that on the second iteration (first is that `server.read` recieves a message and forwards it to the client) I always get this log message and the connection to client closes:
```
2024-06-19T14:50:55.603427Z ERROR ratchet_core::ws: WebSocket read failure: Error { inner: Inner { kind: Protocol, source: Some(ContinuationNotStarted) } }
```
Can you please explain what am I doing wrong here? I tried both with and without deflate extension, but it doesn't seem to make any difference.

**Comment by SirCipher** [comment]
Hi @pdavydov108! 

Thank you for your kind feedback and for raising an issue. I've locally recreated what you're trying to achieve and I cannot reproduce the error. However, I believe what is the cause of your issue is how you are creating the futures using the Tokio `select` macro. 

You're creating a read future in each arm of the macro **every** time the macro runs and it's possible that the other arm will complete first. Then when the loop runs again, the data buffer _may_ be dirty for the corresponding WebSocket as it's previously read part of a frame but the state of the read operation has been reset, causing the error that you're seeing. What you'll need to do is hold on to the read future and await it completing before building another one. Hopefully, that is the cause of the issue. I should have made it clearer in the documentation that the `read` and `write` functions are not cancellation safe - I'll improve the documentation clearer about this.

If it's not, or you need any more help, then please let me know :)

**Comment by SirCipher** [comment]
@pdavydov108, glad you got it sorted. The read and write functions are not cancellation safe for both the owned and split socket implementations. I'll have the documentation updated shortly to reflect this.
