### ISSUE TITLE
Consider relaxing version requirements for tokio in `Cargo.toml`

### ISSUE THREAD

**Issue by nakedible-p** [swimos/ratchet#40]
Currently, you say in the toplevel `Cargo.toml`:

```
tokio = "=1.38.1"
tokio-util = "=0.7.1"
```

Tokio is at 1.40.0, and tokio-util is at 0.7.12. Unless it is absolutely mandatory for these packages, consider relaxing these values so the library is easier to incorporate to existing projects.

**Comment by SirCipher** [comment]
They were incorrectly set that strict due to the supported MSRV but I've relaxed it and bumped the MSRV to 1.70.0 which will support the versions that you've mentioned - Tokio bumped their MSRV which clashed with Ratchet's. I've made a PR with the increase in MSRV and I'll have that pushed through next week.
